config/routes.rb
ProjectAsscociation::Application.routes.draw do
  resources :locations do
  get 'show_locations', to: 'locations#show_locations'
  end
  get "map/index"
  resources :products 
  get 'all_users', to: 'products#all_users'
  get 'product_detail', to: 'products#product_detail'
  devise_for :users 
  get 'destroy_user', to: 'products#destroy_user'
  resources :suppliers do  
    resources :accounts 
    end
    resources :accounts do
      resources :account_histories
      end  
  get "welcome/index"
  post "map/index"

  root to: "welcome#index"
end

app/models/account_history.rb
class AccountHistory < ActiveRecord::Base
  attr_accessible :credit_rating, :account_id
    belongs_to :account
    
end

app/controllers/account_histories_controller.rb
class AccountHistoriesController < ApplicationController
  # GET /account_histories
  # GET /account_histories.json
  def index
    @account_history = AccountHistory.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @account_history }
    end
  end

  # GET /account_histories/1
  # GET /account_histories/1.jsons
  def show
    @account_history = AccountHistory.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account_history }
    end
  end

  # GET /account_histories/new
  # GET /account_histories/new.json
  def new
     @account = Account.find(params[:account_id])
     @account_history = @account.build_account_history
     respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account_history }
    end
  end

  # GET /account_histories/1/edit
  def edit
    @account_history = AccountHistory.find(params[:id])
  end

  # POST /account_histories
  # POST /account_histories.json
  def create
    @account = Account.find(params[:account_id])
    @account_history = @account.create_account_history(params[:account_history])
    respond_to do |format|
      if @account_history.save
        format.html { redirect_to account_account_history_path(@account,@account_history), notice: 'Account history was successfully created.' }
        format.json { render json: @account_history, status: :created, location: @account_history }
      else
        format.html { render action: "new" }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /account_histories/1
  # PUT /account_histories/1.json
  def update
    @account_history = AccountHistory.find(params[:id])

    respond_to do |format|
      if @account_history.update_attributes(params[:account_history])
        format.html { redirect_to @account_history, notice: 'Account history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_histories/1
  # DELETE /account_histories/1.json
  def destroy
    @account_history = AccountHistory.find(params[:id])
    @account_history.destroy

    respond_to do |format|
      format.html { redirect_to account_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/account_histories_helper.rb
module AccountHistoriesHelper
end

app/views/account_histories/_form.html.erb
<%= form_for([@account,@account_history]) do |f| %>
  <% if @account_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account_history.errors.count, "error") %> prohibited this account_history from being saved:</h2>
      <ul>
      <% @account_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :credit_rating %><br />
    <%= f.number_field :credit_rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= @account_history.inspect %>

app/views/account_histories/edit.html.erb
<h1>Editing account_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_history %> |
<%= link_to 'Back', account_histories_path %>

app/views/account_histories/index.html.erb
<h1>Listing account_histories</h1>

<table>
  <tr>
    <th>Credit rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @account_history.each do |account_history| %>
  <tr>
    <td><%= account_history.credit_rating %></td>
    <td><%#= link_to 'Show', account_history %></td>
    <td><%#= link_to 'Edit', edit_account_history_path(account_history) %></td>
    <td><%#= link_to 'Destroy', account_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Account history', new_account_history_path %>

app/views/account_histories/new.html.erb
<h1>New account_history</h1>

<%= render 'form' %>

<%#= link_to 'Back', account_histories_path %>

app/views/account_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Credit rating:</b>
  <%= @account_history.credit_rating %>
</p>
<%#= link_to 'Edit', edit_account_history_path(@account_history) %> 
<%#= link_to 'Back', account_histories_path %>