config/routes.rb
ProjectAsscociation::Application.routes.draw do
  resources :locations do
  get 'show_locations', to: 'locations#show_locations'
  end
  get "map/index"
  resources :products 
  get 'all_users', to: 'products#all_users'
  get 'product_detail', to: 'products#product_detail'
  devise_for :users 
  get 'destroy_user', to: 'products#destroy_user'
  resources :suppliers do  
    resources :accounts 
    end
    resources :accounts do
      resources :account_histories
      end  
  get "welcome/index"
  post "map/index"

  root to: "welcome#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= h(yield(:title) || "Untitled") %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
   <%= javascript_include_tag 'jquery.1.3.2.min' %>
   <%= javascript_include_tag 'jcrop'%>
   <%= javascript_include_tag 'jquery.jcrop'%>
   <%= javascript_include_tag 'jquery.color'%>
   <%= javascript_include_tag 'jquery.jcrop.min'%>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag "jquery.jcrop.min" %>
   <%= stylesheet_link_tag "jquery.jcrop" %>
  <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= javascript_include_tag 'prototype' %>
   <%= stylesheet_link_tag "bootstrap_and_overrides" %>
   <%= yield(:head) %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
<div class="container">
  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Product Store</a>
      <div class="nav-collapse">
        <ul class="nav">
<% if user_signed_in? %>
    <%= link_to 'Sign out', destroy_user_session_path ,:method => :delete %>&nbsp;&nbsp;&nbsp;
            <% if current_user.admin?  %>
             <%= link_to 'Create Product', new_product_path %>&nbsp;&nbsp;&nbsp;
             <%= link_to 'Show all Product', products_path %>&nbsp;&nbsp;&nbsp;
             <%= link_to 'Show all Users' , all_users_path %>&nbsp;&nbsp;&nbsp;
              <%= link_to 'New Location', new_location_path %>&nbsp;&nbsp;&nbsp;
              <%= link_to 'Search Location', locations_path %>&nbsp;&nbsp;&nbsp;
             <% else %>
               <%= link_to 'Show all Product',products_path %>
             <% end %>
    <% else %>
        <%= link_to 'Register', new_user_registration_path %>&nbsp;&nbsp;&nbsp;
         <%= link_to 'Sign in', new_user_session_path %>&nbsp;&nbsp;&nbsp;
    <% end %> 
    <%= yield :scripts %>
        </ul>
      </div>
    </div>
  </div>
</div>
   <div class="row">
    <div class="span9">
      <%= yield %></div>
    <div class="span3">        
    </div>
  </div>
</div>
</div>
</body>
</html>